language: bash

before_install:
  - git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
  - mkdir -p /tmp/local
  - bash /tmp/bats-core/install.sh /tmp/local
  - export PATH=$PATH:/tmp/local/bin
install:
  - sudo apt-get install -qq bc
script:
  - make test
